name: Playwright Smoke Tests (Chromium)

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Build Docker Image
      - name: Build Docker Image
        run: docker build -t funda-playwright-chromium .

      # Step 4: Run Smoke Tests for Chromium
      - name: Run Smoke Tests Chromium
        run: docker run --rm \
          -v ${{ github.workspace }}/playwright-report:/app/playwright-report \
          -e "USER_AGENT=${{ secrets.USER_AGENT }}" \
          -e "LANGUAGE=${{ secrets.LANGUAGE }}" \
          -e "USERNAME=${{ secrets.USERNAME }}" \
          -e "PASSWORD=${{ secrets.PASSWORD }}" \
          funda-playwright-chromium

      # Step 5: Upload Test Report as an Artifact
      - name: Upload Test Report
        uses: actions/upload-artifact@v3
        with:
          name: playwright-report
          path: playwright-report

      # Step 6: Upload Trace Files (for debugging failed tests)
      - name: Upload Trace Files
        uses: actions/upload-artifact@v3
        with:
          name: playwright-traces
          path: test-results/traces # Ensure this path matches the trace output directory in your Playwright config
